### ISSUE TITLE
Need example with array as datasource

### ISSUE THREAD

**Issue by ocgltd** [vitocmpl/ng2-ya-table#6]
Could someone add an example/demo with a simple array as the data source?  This question was posted on StackOverflow months ago and is unanswered.  This would make ng2-ya-table usable for a wider audience.

**Comment by vitocmpl** [comment]
The data source is an Observable in order to support pagination, ordering, and filtering server side.
I wrote a simple .NET library to support this [ng2-ya-table.DataSource.Core](https://github.com/vitocmpl/ng2-ya-table.DataSource.Core).

Anyway, you can manage a simple array in this way:

```typescript
public datasource: any = (request: any): Observable<any> => {
  let page = (request.start * request.length) + 1;
  let _data = this.data.slice(request.length * (page - 1), request.length * page);

  return Observable.of({
    recordsTotal: _data.length,
    recordsFiltered: _data.length,
    data: _data
  });
}
```
The example support only the pagination.

I'm looking to implement a built-in local datasource to also support filtering and sorting.

**Comment by vitocmpl** [comment]
The latest version now supports the local data source natively.

```xml
<ng2-ya-table [options]="options" [columns]="columns" [datasource]="data" [paging]="paging">
</ng2-ya-table>
```

```typescript
public data: Array<any> = [...]; //array of data
```
